"
  CREATE TABLE "RTIWARI"."GRIEVANCE_ATTACHMENTS" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"GRIEVANCE_ID" RAW(16), 
	"FILE_NAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"FILE_PATH" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"FILE_TYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"FILE_SIZE" NUMBER(15,0), 
	"UPLOADED_BY" RAW(16), 
	"UPLOADED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."USER_PAGE_OVERRIDES" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" RAW(16), 
	"MODULE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PAGE_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CAN_VIEW" NUMBER(1,0), 
	"CAN_EXPORT" NUMBER(1,0), 
	"UPDATED_BY" RAW(16), 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."GRIEVANCES" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"GRIEVANCE_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" RAW(16), 
	"STATE_CODE" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"DISTRICT_CODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"ASSIGNED_TO" RAW(16), 
	"CATEGORY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SUB_CATEGORY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBJECT" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" CLOB COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'OPEN', 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"RESOLVED_AT" TIMESTAMP (6)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;"
"
  CREATE TABLE "RTIWARI"."GRIEVANCE_HISTORY" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"GRIEVANCE_ID" RAW(16), 
	"ACTION" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"OLD_STATUS" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"NEW_STATUS" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"COMMENTS" CLOB COLLATE "USING_NLS_COMP", 
	"IS_INTERNAL" NUMBER(1,0) DEFAULT 0, 
	"PERFORMED_BY" RAW(16), 
	"PERFORMED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("COMMENTS") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;"
"
  CREATE TABLE "RTIWARI"."GRIEVANCE_RESPONSES" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"GRIEVANCE_ID" RAW(16), 
	"RESPONSE_TEXT" CLOB COLLATE "USING_NLS_COMP", 
	"RESPONDED_BY" RAW(16), 
	"RESPONDED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("RESPONSE_TEXT") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;"
"
  CREATE TABLE "RTIWARI"."VSK_PMU_ROLE_STRUCTURE" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"HEADER_ID" RAW(16), 
	"ROLE_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CUSTOM_ROLE_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"NO_OF_MEMBERS" NUMBER(5,0), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."VSK_COMMITTEE_MEMBER" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"STATE_CODE" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"DESIGNATION" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PHONE" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP", 
	"WHATSAPP" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_BY" RAW(16), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_BY" RAW(16), 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."VSK_GALLERY_IMAGES" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"STATE_CODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"FILE_NAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"FILE_PATH" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"THUMBNAIL_PATH" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"CAPTION" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"FILE_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"FILE_SIZE" NUMBER(15,0), 
	"UPLOADED_BY" RAW(16), 
	"UPLOADED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."ACTIVITY_LOG" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"MODULE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ACTION" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"ENTITY_ID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PERFORMED_BY" RAW(16), 
	"PERFORMED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"STATE_CODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."VSK_OFFICER_HISTORY" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"STATE_CODE" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"OFFICER_ROLE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"DESIGNATION" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PHONE" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP", 
	"WHATSAPP" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_BY" RAW(16), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_BY" RAW(16), 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."PAGE_MASTER" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"MODULE_ID" RAW(16), 
	"PAGE_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PAGE_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ROUTE_PATH" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ICON" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"DISPLAY_ORDER" NUMBER(5,0), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_BY" RAW(16), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."ROLE_PAGE_DEFAULTS_V2" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"ROLE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PAGE_ID" RAW(16), 
	"CAN_VIEW" NUMBER(1,0) DEFAULT 1, 
	"CAN_EDIT" NUMBER(1,0) DEFAULT 0, 
	"CAN_EXPORT" NUMBER(1,0) DEFAULT 0, 
	"CAN_DELETE" NUMBER(1,0) DEFAULT 0, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."FORM_MASTER" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"TITLE" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" CLOB COLLATE "USING_NLS_COMP", 
	"INSTRUCTIONS" CLOB COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'DRAFT', 
	"DUE_DATE" TIMESTAMP (6), 
	"PUBLISH_DATE" TIMESTAMP (6), 
	"CREATED_BY" RAW(16), 
	"CREATED_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_BY" RAW(16), 
	"UPDATED_DATE" TIMESTAMP (6)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("INSTRUCTIONS") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;"
"
  CREATE TABLE "RTIWARI"."FORM_AUDIT" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"FORM_ID" RAW(16), 
	"ACTION" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_ID" RAW(16), 
	"ACTION_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."FORM_QUESTION" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"FORM_ID" RAW(16), 
	"QUESTION_TEXT" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"FIELD_TYPE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_REQUIRED" NUMBER(1,0) DEFAULT 0, 
	"HELP_TEXT" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"OPTIONS_JSON" CLOB COLLATE "USING_NLS_COMP", 
	"DISPLAY_ORDER" NUMBER(5,0), 
	"CREATED_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("OPTIONS_JSON") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;"
"
  CREATE TABLE "RTIWARI"."FORM_ASSIGNMENT" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"FORM_ID" RAW(16), 
	"STATE_CODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBMISSION_STATUS" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'PENDING', 
	"ASSIGNED_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"SUBMITTED_DATE" TIMESTAMP (6), 
	"SUBMITTED_BY" RAW(16)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."FORM_ATTACHMENTS" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"FORM_ID" RAW(16), 
	"RESPONSE_ID" RAW(16), 
	"FILE_NAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"FILE_PATH" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"FILE_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"FILE_SIZE" NUMBER(15,0), 
	"UPLOADED_BY" RAW(16), 
	"UPLOADED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."VSK_PROFILE" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"STATE_CODE" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS_LINE1" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS_LINE2" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"CITY" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PINCODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"FACILITATED_BY" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"OTHER_SCHEME_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"STEP1_STATUS" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'PENDING', 
	"STEP2_STATUS" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'PENDING', 
	"STEP3_STATUS" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'PENDING', 
	"STEP4_STATUS" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'PENDING', 
	"SUBMISSION_STATUS" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'DRAFT', 
	"DECLARATION_CERTIFIED" NUMBER(1,0) DEFAULT 0, 
	"CREATED_BY" RAW(16), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_BY" RAW(16), 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."VSK_INFRA_HARDWARE" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"STATE_CODE" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"ROOM_LENGTH" NUMBER(10,2), 
	"ROOM_WIDTH" NUMBER(10,2), 
	"ROOM_HEIGHT" NUMBER(10,2), 
	"ROOM_IMAGE_URL" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"SCREEN_LENGTH" NUMBER(10,2), 
	"SCREEN_HEIGHT" NUMBER(10,2), 
	"SCREEN_IMAGE_URL" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"WORKSTATION_COUNT" NUMBER(5,0), 
	"WORKSTATION_IMAGE_URL" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" RAW(16), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_BY" RAW(16), 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."MODULE_MASTER" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"MODULE_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"MODULE_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ICON" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"DISPLAY_ORDER" NUMBER(5,0), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_BY" RAW(16), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."GRIEVANCE_CATEGORIES" 
   (	"CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"LABEL" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PARENT_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SORT_ORDER" NUMBER(5,0) DEFAULT 0, 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."ROLE_PAGE_DEFAULTS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ROLE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"MODULE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PAGE_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CAN_VIEW" NUMBER(1,0) DEFAULT 1, 
	"CAN_EXPORT" NUMBER(1,0) DEFAULT 0, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."DISTRICT_MASTER" 
   (	"DISTRICT_CODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"DISTRICT_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DISTRICT_NAME_LOCAL" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"STATE_CODE" CHAR(2 BYTE) COLLATE "USING_NLS_COMP", 
	"LGD_CODE" NUMBER(10,0), 
	"DISTRICT_TYPE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"HEADQUARTERS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."BLOCK_MASTER" 
   (	"BLOCK_CODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"BLOCK_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"BLOCK_NAME_LOCAL" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DISTRICT_CODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"LGD_CODE" NUMBER(10,0), 
	"BLOCK_TYPE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_URBAN" NUMBER(1,0) DEFAULT 0, 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."PORTAL_USERS" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"USERNAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"DISPLAY_NAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PASSWORD_HASH" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"ROLE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"STATE_CODE" CHAR(2 BYTE) COLLATE "USING_NLS_COMP", 
	"DISTRICT_CODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"FAILED_ATTEMPTS" NUMBER(5,0) DEFAULT 0, 
	"LOCKED_UNTIL" TIMESTAMP (6), 
	"LAST_LOGIN_AT" TIMESTAMP (6), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"IS_FIRST_LOGIN" NUMBER(1,0) DEFAULT 1, 
	"PHONE" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP", 
	"DESIGNATION" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DEPARTMENT" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PASSWORD_CHANGED_AT" TIMESTAMP (6), 
	"CREATED_BY" RAW(16), 
	"USER_EMAIL" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_EMAIL" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"MOBILE_NUMBER" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."VSK_SOFTWARE_HEADER" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"STATE_CODE" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"STARTER_PACK" NUMBER(1,0) DEFAULT 0, 
	"SERVER_TYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" RAW(16), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_BY" RAW(16), 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."VSK_SOFTWARE_ITEM" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"HEADER_ID" RAW(16), 
	"SOFTWARE_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CUSTOM_SOFTWARE_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"SOFTWARE_TYPE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."VSK_AUDIT_LOG" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"ENTITY_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ENTITY_ID" RAW(16), 
	"ACTION_TYPE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"OLD_VALUES" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NEW_VALUES" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_ID" RAW(16), 
	"USER_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_STATE_CODE" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."VSK_PMU_HEADER" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"STATE_CODE" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"PMU_TEAM_TYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TOTAL_TEAM_MEMBERS" NUMBER(5,0), 
	"CREATED_BY" RAW(16), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_BY" RAW(16), 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."STATE_MASTER" 
   (	"STATE_CODE" CHAR(2 BYTE) COLLATE "USING_NLS_COMP", 
	"STATE_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"STATE_NAME_LOCAL" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"STATE_TYPE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'STATE', 
	"LGD_CODE" NUMBER(10,0), 
	"CAPITAL" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"REGION" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."CLUSTER_MASTER" 
   (	"CLUSTER_CODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CLUSTER_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"BLOCK_CODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."USER_PAGE_OVERRIDES_V2" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"USER_ID" RAW(16), 
	"PAGE_ID" RAW(16), 
	"CAN_VIEW" NUMBER(1,0), 
	"CAN_EDIT" NUMBER(1,0), 
	"CAN_EXPORT" NUMBER(1,0), 
	"CAN_DELETE" NUMBER(1,0), 
	"UPDATED_BY" RAW(16), 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."FORM_RESPONSE" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"FORM_ID" RAW(16), 
	"STATE_CODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBMITTED_BY" RAW(16), 
	"SUBMITTED_DATE" TIMESTAMP (6), 
	"STATUS" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'DRAFT'
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  TABLESPACE "DATA" ;"
"
  CREATE TABLE "RTIWARI"."FORM_RESPONSE_DETAIL" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"RESPONSE_ID" RAW(16), 
	"QUESTION_ID" RAW(16), 
	"ANSWER_VALUE" CLOB COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  TABLESPACE "DATA" 
 LOB ("ANSWER_VALUE") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;"