/**
 * JWT token payload structure — mirrors the claims embedded in both
 * access and refresh tokens generated by the Auth service.
 */
export interface JwtPayload {
  /** Username (subject) */
  sub: string;
  /** User role, e.g. "Super_Admin", "RVSK_SPOC" */
  role: string;
  /** 2-character state code (empty string when null in DB) */
  state_code: string;
  /** UUID string identifying the user */
  user_id: string;
  /** Discriminator: "access" for API auth, "refresh" for token renewal */
  token_type: 'access' | 'refresh';
  /** Module-code → page-code[] permission map (access tokens only) */
  access?: Record<string, string[]>;
  /** Issued-at (epoch seconds) */
  iat: number;
  /** Expiration (epoch seconds) */
  exp: number;
}

/**
 * Authenticated user object attached to the request after JWT validation.
 * Extracted from the JWT payload by JwtStrategy.validate().
 */
export interface AuthenticatedUser {
  userId: string;
  username: string;
  role: string;
  stateCode: string;
  access?: Record<string, string[]>;
}
